name: ✝️ Update Bible Verse Daily

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Bible Verse
        run: |
          curl https://beta.ourmanna.com/api/v1/get/?format=text > verse.txt

      - name: Update README
        run: |
          VERSE=$(cat verse.txt)
          echo "Updating README.md with Bible verse: $VERSE"

          awk -v verse="$VERSE" '
            BEGIN { found=0 }
            /<!-- BIBLE-VERSE-START -->/ {
              print
              print ""
              print "> **" verse "**"
              found=1
              next
            }
            /<!-- BIBLE-VERSE-END -->/ {
              found=0
            }
            !found
          ' README.md > README_temp.md

          mv README_temp.md README.md

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "⛪ Updated daily Bible verse"
          git push
